# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pz1zAVi7q1acnOiJjHRcYSs-uNSORFw1
"""

class Rectangle :
    n_edges = 4

    def __init__(self, length, width):
        self.length = length
        self.width = width

    def rectangle_area(self):
      return self.length*self.width

    def rectangle_perimeter(self):
      return (2*self.length)+(2*self.width)

    @staticmethod
    def talk():
      print("Do you like rectangles?")
  

class Patch :
    def __str__(self,x):
      self.x = x
      self.y = x

    def __iter__(self):
      return self