# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pz1zAVi7q1acnOiJjHRcYSs-uNSORFw1
"""

class Sentence :
    def __init__(self, text):
        self.text = text
        self.word_list = self.text.split()

    def get_all_words(self):
       for word in self.word_list:
        print(word)
    
    def __str__(self):
      return 'Sentence(text=' + self.text + ')'